In [5]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile,join
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#print(face_classifier)
def face_extractor(img):
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_classifier.detectMultiScale(gray,1.3,5)
    print(faces)
    #print(np.shape(faces))
    if faces is():
         return None
    for(x,y,w,h) in faces:
        cropped_face=img[y:y+h,x:x+w]
    return cropped_face
cap=cv2.VideoCapture(0)
count=0
while True:
    ret, frame=cap.read()
    if face_extractor(frame) is not None:
        count+=1
        face=cv2.resize(face_extractor(frame),(200,200))
        face=cv2.cvtColor(face,cv2.COLOR_BGR2GRAY)
        data_path='C:/Users/Dell/Sample' +str(count) +'.jpg'
        cv2.imwrite(data_path,face)
        cv2.putText(face,str(count),(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        cv2.imshow('Face Cropper',face)
    else:
        print('face not found')
        pass
    if cv2.waitKey(1)==13 or count==100:
        break
cap.release()
cv2.destroyAllWindows()
print('collecting samples complete!!')
path='C:/Users/Dell/'
onlyfiles=[f for f in listdir(path) if isfile(join(path,f))]
Training_Data,Labels=[],[]
for i, files in enumerate(onlyfiles):
    image_path=path + onlyfiles[i]
    images=cv2.imread(image_path,cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images,dtype=np.string))
    Labels.append(i)
Labels=np.asarray(Labels,dtype=np.int32)
model= cv2.face.LBPHFaceRecognizer_create()
model.train(np.asarray(Training_Data),np.asarray(Labels))
print("Model training complete")
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
def face_detector(img,size=0.5):
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_classifier.detectMultiScale(gray,1.3,5)
    if faces is():
        return img,[]
    for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi=img[y:y+h,x:x+w]
        roi=cv2.resize(roi,(200,200))
    return img,roi
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()

    image,face=face_detector(frame)
    try:
        face=cv2.cvtColor(face,cv2.COLOR_BGR2GRAY)
        result=model.predict(face)
        if result[1] < 500:
            definately=int(100*(1-(result[1])/400))

            display_string=str(definately)+'% definately it is user'
        cv2.putText(image,display_string,(100,120),cv2.FONT_HERSHEY_COMPLEX,1,(250,120,150),2)

        if definately>75:
            cv2.putText(image,"Unlocked",(250,450),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
            cv2.imshow('Face Cropper',image)
        else:
            cv2,putText(image,"locked",(250,450),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
    except:
        cv2.putText(image,"Face not found",(220,120),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
        #cv2.putText(image,"Locked",(250,450),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
  
        cv2.imshow('Face Cropper',image)
        pass
    if cv2.waitKey(1)==13:
        break
cap.release()
cv2.destroyAllWindows()

[[301 240 217 217]]
[[301 240 217 217]]
[[301 243 215 215]]
[[301 243 215 215]]
[[300 242 213 213]]
[[300 242 213 213]]
[[301 242 215 215]]
[[301 242 215 215]]
[[300 242 215 215]]
[[300 242 215 215]]
[[299 242 216 216]]
[[299 242 216 216]]
[[299 241 216 216]]
[[299 241 216 216]]
[[301 244 212 212]]
[[301 244 212 212]]
[[281 134 255 255]
 [301 243 214 214]]
[[281 134 255 255]
 [301 243 214 214]]
[[300 241 215 215]]
[[300 241 215 215]]
[[281 134 255 255]
 [301 242 213 213]]
[[281 134 255 255]
 [301 242 213 213]]
[[298 243 213 213]]
[[298 243 213 213]]
[[301 244 210 210]]
[[301 244 210 210]]
[[301 242 216 216]]
[[301 242 216 216]]
[[300 242 213 213]]
[[300 242 213 213]]
[[300 244 212 212]]
[[300 244 212 212]]
[[300 243 213 213]]
[[300 243 213 213]]
[[301 244 210 210]]
[[301 244 210 210]]
[[300 245 211 211]]
[[300 245 211 211]]
[[300 242 214 214]]
[[300 242 214 214]]
[[300 243 214 214]]
[[300 243 214 214]]
[[300 243 211 211]]
[[300 243 211 211]]
[[300 244 211 211]]
[[300 244 211 211]]
[[30

AttributeError: module 'numpy' has no attribute 'string'

In [1]:
pip install opencv-contrib-python

  Using cached https://files.pythonhosted.org/packages/00/a3/dfdbd5db6ba7f5b5a34d969c7508866c48826c61eb5e2c913d27f8784ff4/opencv_contrib_python-4.1.1.26-cp37-cp37m-win_amd64.whl
Note: you may need to restart the kernel to use updated packages.


In [5]:
pwd

'C:\\Users\\Dell'

In [4]:
import cv2
import matplotlib.pyplot as plt

num_of_sample=200
vid=cv2.VideoCapture(0) #to open the camera
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

iter1=0
while(iter1<num_of_sample):
    r,frame=vid.read();
    frame=cv2.resize(frame,(640,480)) #resizing the frame
    im1=cv2.cvtColor(frame,cv2.COLOR_RGB2GRAY) #gray scale conversion of color image
    face=face_cascade.detectMultiScale(im1)
    for x,y,w,h in(face):
        cv2.rectangle(frame,(x,y),(x+w,y+h),[255,0,0],4)
        iter1+=1
        im_f=im1[y:y+h,x:x+w]
        im_f=cv2.resize(im_f,(112,92))
        cv2.putText(frame,'face No. '+str(iter1),(x,y), cv2.FONT_ITALIC, 1,
                    (255,0,255),2,cv2.LINE_AA)
        path = 'C:/Users/Dell/%d.png'%(iter1) #path to save the image
        cv2.imwrite(path,im_f)  #to save the image

cv2.imshow('frame',frame)
cv2.waitKey(1)
vid.release()
cv2.destroyAllWindows()

